// Arabic strings. Keys are the English text shown in the game; anything missing here stays in English.
export const AR = {
  'Play': 'العب', 'Garage': 'الجراج', 'Tuning': 'الضبط', 'Online': 'أونلاين', 'Trophies': 'الكؤوس', 'Settings': 'الإعدادات', 'credits': 'رصيد',
  'Race': 'سباق', 'Grand Prix': 'الجائزة الكبرى', 'Time trial': 'ضد الزمن', 'Drift': 'تفحيط', 'Circuit rules': 'قواعد الحلبة', 'Arcade rules': 'قواعد الأركيد',
  'Daily challenge': 'تحدي اليوم', 'Laps': 'اللفات', 'Rivals': 'المنافسون', 'Easy': 'سهل', 'Medium': 'متوسط', 'Hard': 'صعب', 'Dry': 'جاف', 'Changeable': 'متقلب', 'Rain': 'مطر',
  'Start race': 'ابدأ السباق', 'Start time trial': 'ابدأ ضد الزمن', 'Start drift attack': 'ابدأ التفحيط', 'Start Grand Prix': 'ابدأ الجائزة الكبرى', 'Continue': 'أكمل', 'Round': 'الجولة',
  'Car locked': 'السيارة مقفلة', 'Unlock for': 'افتح بـ', 'Join a room first': 'ادخل غرفة أولاً', 'Waiting for rival': 'في انتظار المنافس', 'Start duel': 'ابدأ المبارزة', 'Host starts the race': 'المضيف يبدأ السباق',
  'Paint': 'الطلاء', 'Upgrades': 'الترقيات', 'Rear wing': 'الجناح الخلفي', 'None': 'بدون', 'Lip': 'حافة', 'GT wing': 'جناح GT', 'Race wing': 'جناح سباق', 'Front splitter': 'المشتت الأمامي', 'Off': 'إيقاف', 'On': 'تشغيل',
  'Wheels': 'الجنوط', 'Glass': 'الزجاج', 'Underglow': 'إضاءة سفلية', 'Engine': 'المحرك', 'Tyres': 'الإطارات', 'Nitro': 'نيترو', 'Armour': 'الدرع',
  'Car set-up': 'ضبط السيارة', 'Gearing': 'نسب التروس', 'Top speed': 'السرعة القصوى', 'Acceleration': 'التسارع', 'Downforce': 'القوة السفلية', 'Less drag': 'مقاومة أقل', 'More grip': 'تماسك أكثر',
  'Brake bias': 'توزيع الفرامل', 'Rearward': 'للخلف', 'Forward': 'للأمام', 'Balance': 'التوازن', 'Agile': 'رشيقة', 'Stable': 'ثابتة', 'Tyre compound': 'نوع الإطار', 'Soft': 'لين', 'Hard ': 'قاسٍ',
  'Soft tyres grip more and wear faster. Hard tyres last longer. Settings apply to this car only.': 'الإطارات اللينة تتماسك أكثر وتتآكل أسرع، والقاسية تدوم أطول. الضبط يخص هذه السيارة فقط.',
  'Language': 'اللغة', 'Driver name': 'اسم السائق', 'Camera distance': 'بُعد الكاميرا', 'Close': 'قريب', 'Normal': 'عادي', 'Far': 'بعيد', 'Very far': 'بعيد جداً', 'Speed units': 'وحدة السرعة',
  'Music': 'الموسيقى', 'Sound effects': 'المؤثرات', 'Reset progress': 'مسح التقدم', 'Erase all progress, cars and settings?': 'مسح كل التقدم والسيارات والإعدادات؟',
  'Create room': 'أنشئ غرفة', 'or': 'أو', 'Join': 'انضم', 'Room': 'الغرفة', 'copy invite link': 'انسخ رابط الدعوة', 'leave': 'خروج',
  'Speed': 'السرعة', 'Launch': 'الانطلاق', 'Grip': 'التماسك',
  'Pos': 'المركز', 'Lap': 'لفة', 'Best': 'الأفضل', 'Car': 'السيارة', 'Fuel': 'الوقود', 'Wets': 'مطر',
  'Paused': 'إيقاف مؤقت', 'Resume': 'استمر', 'Restart': 'أعد', 'Back to menu': 'القائمة', 'Menu': 'القائمة', 'Race again': 'سباق آخر', 'Next round': 'الجولة التالية', 'Finish': 'إنهاء',
  'Winner': 'الفائز', 'Standings': 'الترتيب', 'Grand Prix champion': 'بطل الجائزة الكبرى', 'Grand Prix finished': 'انتهت الجائزة الكبرى',
  'Four rounds, eight drivers, points for every finish. The third round is wet.': 'أربع جولات وثمانية سائقين ونقاط لكل مركز. الجولة الثالثة تحت المطر.',
  'Knockout': 'الإقصاء', 'Endurance': 'التحمل', 'Start knockout': 'ابدأ الإقصاء', 'Start endurance': 'ابدأ التحمل', 'is out': 'خرج', 'Knocked out': 'تم إقصاؤك', 'Side skirts': 'جوانب', 'Roof scoop': 'فتحة السقف', 'Exhaust tips': 'عوادم', 'Traction control': 'منع الانزلاق', 'Steering': 'التوجيه', 'Calm': 'هادئ', 'Sharp': 'حاد',
  'Burnout': 'حرق إطارات', 'Wheelspin': 'دوران العجلات', 'Oversteer': 'انزلاق خلفي', 'Understeer': 'انزلاق أمامي', 'Slipstream': 'سحب هوائي',
  'Professional': 'احترافي', 'Arcade': 'أركيد', 'Daily box': 'صندوق اليوم', 'A car, an upgrade, XP or credits': 'سيارة أو ترقية أو خبرة أو رصيد', 'Open now': 'افتحه الآن', 'Come back tomorrow': 'عد غداً', 'Collect': 'استلم', 'New car': 'سيارة جديدة', 'Free upgrade': 'ترقية مجانية', 'Driver XP': 'خبرة السائق', 'Credits': 'رصيد', 'Your pit box': 'موقفك', 'laps of fuel': 'لفات وقود', 'is towed in': 'سُحبت إلى الصيانة', 'Engine': 'المحرك', 'Gearbox': 'ناقل الحركة', 'Bodywork': 'الهيكل',
  'Engine': 'المحرك',
  'Pace': 'الإيقاع', 'Save': 'توفير', 'Push': 'هجوم', 'Delta': 'الفارق',
  'Safety car': 'سيارة الأمان', 'no overtaking': 'ممنوع التجاوز', 'Green flag': 'علم أخضر', 'This car has its own wing.': 'هذه السيارة لها جناحها الخاص.',
  'penalty': 'عقوبة', 'class': 'فئة', 'Touring': 'سياحية', 'GT': 'جي تي', 'Super': 'خارقة',
  'Livery': 'الطلاء', 'Plain': 'سادة', 'Stripes': 'خطوط', 'Roof': 'السقف', 'Roof + stripes': 'سقف وخطوط', 'Race number': 'رقم السباق', 'None': 'بدون', 'Effect of this set-up': 'أثر هذا الضبط', 'Stock': 'الأصلي', 'Now': 'الآن', 'Utility': 'خدمية', 'Formula': 'فورمولا',
  'Flash': 'وميض', 'Nose': 'الأنف', 'Full': 'كامل',
  'Game mode': 'نمط اللعب', 'Rules': 'القواعد', 'Today': 'اليوم', 'Race setup': 'إعداد السباق', 'Difficulty': 'الصعوبة', 'Weather': 'الطقس', 'Profile': 'الملف الشخصي', 'Driving assists': 'مساعدات القيادة', 'Display': 'العرض', 'Audio': 'الصوت', 'Data': 'البيانات',
  'Group B': 'المجموعة B', 'Group A': 'المجموعة A', 'Classic': 'كلاسيكي',
  'Torque split': 'توزيع العزم',
  'Rear-biased': 'للخلف',
  'Front-biased': 'للأمام',
  'Differential': 'الدفرنشيال',
  'Open': 'مفتوح',
  'Locked': 'مقفول',
  'Gravel': 'جرافيل',
  'Exit traction': 'التماسك عند الخروج',
  'Nose push on power': 'ميل المقدمة عند التسارع',
  'Front torque share': 'عزم المحور الأمامي',
  'Soft tyres grip more and wear faster; hard tyres last longer and need more heat. Rain tyres for wet roads, gravel tyres for loose ground. Watch the tyre temperature: too cold or too hot and the grip falls away. Settings apply to this car only.': 'الإطارات اللينة تتماسك أكثر وتتآكل أسرع؛ الصلبة تدوم أطول وتحتاج حرارة أكثر. إطارات المطر للطرق المبللة وإطارات الجرافيل للأرض الرخوة. راقب حرارة الإطارات: إن كانت باردة جداً أو ساخنة جداً يضعف التماسك. الإعدادات تخص هذه السيارة فقط.',
  'Edit touch controls': 'تعديل أزرار اللمس',
  'Drag every button where your thumbs want it.': 'اسحب كل زر إلى المكان الذي يناسب إبهامك.',
  'Size': 'الحجم',
  'Opacity': 'الشفافية',
  'Left-handed': 'لليد اليسرى',
  'Reset': 'إعادة',
  'Done': 'تم',
  'Rim design': 'تصميم الرنجات',
  'Tyre sidewall': 'جدار الإطار',
  'Brake calipers': 'كاليبر الفرامل',
  'Classic 5-spoke': 'كلاسيك ٥ أذرع',
  'Rally 10-spoke': 'رالي ١٠ أذرع',
  'Mesh': 'شبكي',
  'Twin 7-spoke': '٧ أذرع مزدوجة',
  'Turbofan': 'توربو فان',
  'Steel dish': 'صاج',
  'Deep dish 6': 'عميق ٦ أذرع',
  'Y-spoke': 'ذراع Y',
  'Lettering': 'كتابة',
  'White wall': 'جدار أبيض',
  'Red line': 'خط أحمر',
  'Yellow line': 'خط أصفر',
  'Blood': 'الدم',
  'Race engineer voice': 'صوت مهندس السباق',
  'Car damage': 'أضرار السيارة',
  'Gameplay': 'اللعب',
  'Low': 'منخفض',
  'High': 'عالٍ',
  'Voice': 'الصوت',
  'Radio male': 'راديو - رجل',
  'Radio female': 'راديو - امرأة',
  'Device voice': 'صوت الجهاز',
  'Go': 'انطلق', 'Final lap': 'اللفة الأخيرة', 'Wrong way': 'اتجاه خاطئ', 'Repaired': 'تم الإصلاح', 'Combo lost': 'ضاعت السلسلة',
  'Lights out. Clean first corner.': 'انطفأت الأضواء. خُذ المنعطف الأول بهدوء.', 'Last lap. Everything you have.': 'اللفة الأخيرة. أعطِ كل ما عندك.',
  'Tyres are nearly gone. Box at the blue pit.': 'الإطارات انتهت تقريباً. ادخل الصيانة.', 'Fuel is low. Box this lap or you will not make it.': 'الوقود قليل. ادخل الصيانة هذه اللفة.',
  'We are out of fuel. Coast it to the pit lane.': 'انتهى الوقود. تدحرج إلى ممر الصيانة.', 'Rain. Brake earlier — box for wet tyres if it gets heavy.': 'مطر. افرمل مبكراً وادخل لإطارات المطر إن اشتد.',
  'Limiter on. Nothing to do — drive through.': 'محدد السرعة يعمل. لا شيء مطلوب، أكمل.', 'Invite link copied': 'تم نسخ رابط الدعوة',
  'The home circuit. A full pit lane, a fast first sector, a chicane and two hairpins.': 'حلبة الدار. ممر صيانة كامل وقطاع أول سريع وشيكان ومنعطفان حادان.',
  'Your scanned kart circuit. Tight, technical, tyre walls everywhere.': 'حلبة الكارتينج الممسوحة. ضيقة وتقنية وحواجز الإطارات في كل مكان.',
  'Fast sweepers under the pyramids. Sand runoff eats your speed.': 'منعطفات سريعة تحت الأهرامات، والرمل يسرق سرعتك.',
  'A long seafront blast into a knot of hairpins at sunset.': 'خط مستقيم طويل على البحر ثم عقدة منعطفات عند الغروب.',
  'Street circuit after dark. Square corners, neon walls, no mercy.': 'حلبة شوارع ليلية. زوايا حادة وجدران نيون بلا رحمة.',
};
